### ISSUE TITLE
Receiver Notifications

### ISSUE THREAD

**Issue by Tak2607** [DarrenJDocherty/telegram#4]
Hello there, 
Am I the only one that don't have the notification when I receive a Telegram ? 
Instead, I got, the "You received a Telegram" Notification when i Send one ... 

Any help would be helpful, thanks for you share and your support ;) 
Have a nice day ;)

PS : I'm using RedemRp

**Comment by DarrenJDocherty** [comment]
Hey, sorry, I've only now just seen this but it should be fixed in the most recent version. Thanks for letting me know.
